package whatsnear.hackathon.com.whatsnear;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ListView;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

public class MainActivity2 extends AppCompatActivity {

    // List view
    private ListView lv;

    // Listview Adapter
    ArrayAdapter<String> adapter;

    // Search EditText
    EditText inputSearch;


    // ArrayList for Listview
    ArrayList<HashMap<String, String>> productList;

    static String data = "{\n"
            + "    \"CodeMantra\": [{\n"
            + "        \"text\": \"Loved Marathi Play #CodeMantra (adapted from *A Few Good Men*)\\nEngrossing Drama\\nExcellent Acting\\nTechnically Superb\\n\\\"Must Watch\\\"\\n@muktabarve\",\n"
            + "        \"name\": \"vikramwkarve\",\n"
            + "        \"time\": \"Sat Jun 24 10:31:36 +0000 2017\"\n"
            + "    }],\n"
            + "    \"MJ\": [{\n"
            + "        \"text\": \"❤TIGGY we know U gonna make #MJ proud!\uD83C\uDFA9\uD83D\uDE0D #TigerMJTribute #tigerians LOVE&amp;SUPPORT\uD83D\uDE4C @iTIGERSHROFF @TeamTIGERSHROFF… https://t.co/AhS21ErQN6\",\n"
            + "        \"name\": \"itigershroff_fp\",\n"
            + "        \"time\": \"Sat Jun 24 10:31:11 +0000 2017\"\n"
            + "    }],\n"
            + "    \"TigerMJTribute\": [{\n"
            + "        \"text\": \"❤TIGGY we know U gonna make #MJ proud!\uD83C\uDFA9\uD83D\uDE0D #TigerMJTribute #tigerians LOVE&amp;SUPPORT\uD83D\uDE4C @iTIGERSHROFF @TeamTIGERSHROFF… https://t.co/AhS21ErQN6\",\n"
            + "        \"name\": \"itigershroff_fp\",\n"
            + "        \"time\": \"Sat Jun 24 10:31:11 +0000 2017\"\n"
            + "    }],\n"
            + "    \"tigerians\": [{\n"
            + "        \"text\": \"❤TIGGY we know U gonna make #MJ proud!\uD83C\uDFA9\uD83D\uDE0D #TigerMJTribute #tigerians LOVE&amp;SUPPORT\uD83D\uDE4C @iTIGERSHROFF @TeamTIGERSHROFF… https://t.co/AhS21ErQN6\",\n"
            + "        \"name\": \"itigershroff_fp\",\n"
            + "        \"time\": \"Sat Jun 24 10:31:11 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Pune\": [{\n"
            + "        \"text\": \"BCCI Women, @bcciwomen is now trending in #Pune\\n\\nhttps://t.co/tSvnasj0ck https://t.co/AWxl8NgVox\",\n"
            + "        \"name\": \"TrendsPune\",\n"
            + "        \"time\": \"Sat Jun 24 10:27:12 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"Join the Mastercard team! See our latest #job opening here: https://t.co/3VJmMjlMk6 #OpenSource #Pune, MH #Hiring #CareerArc\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 10:26:31 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"This #job might be a great fit for you: Technical Architect - Java J2EE, Android or iOS - https://t.co/eX1uyehrZW #OpenSource #Pune, MH\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 10:00:29 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"Can you recommend anyone for this #job in #Pune, MH? https://t.co/5Nwj6VtI9k #Hiring\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 09:34:07 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"We're #hiring! Click to apply: Sr Technical Supp Analyst - India - https://t.co/wph1jax1XY #IT #Pune #Job #Jobs\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 09:08:02 +0000 2017\"\n"
            + "    }],\n"
            + "    \"job\": [{\n"
            + "        \"text\": \"Join the Mastercard team! See our latest #job opening here: https://t.co/3VJmMjlMk6 #OpenSource #Pune, MH #Hiring #CareerArc\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 10:26:31 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"This #job might be a great fit for you: Technical Architect - Java J2EE, Android or iOS - https://t.co/eX1uyehrZW #OpenSource #Pune, MH\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 10:00:29 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"Can you recommend anyone for this #job in #Pune, MH? https://t.co/5Nwj6VtI9k #Hiring\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 09:34:07 +0000 2017\"\n"
            + "    }],\n"
            + "    \"OpenSource\": [{\n"
            + "        \"text\": \"Join the Mastercard team! See our latest #job opening here: https://t.co/3VJmMjlMk6 #OpenSource #Pune, MH #Hiring #CareerArc\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 10:26:31 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"This #job might be a great fit for you: Technical Architect - Java J2EE, Android or iOS - https://t.co/eX1uyehrZW #OpenSource #Pune, MH\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 10:00:29 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Hiring\": [{\n"
            + "        \"text\": \"Join the Mastercard team! See our latest #job opening here: https://t.co/3VJmMjlMk6 #OpenSource #Pune, MH #Hiring #CareerArc\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 10:26:31 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"Can you recommend anyone for this #job in #Pune, MH? https://t.co/5Nwj6VtI9k #Hiring\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 09:34:07 +0000 2017\"\n"
            + "    }],\n"
            + "    \"CareerArc\": [{\n"
            + "        \"text\": \"Join the Mastercard team! See our latest #job opening here: https://t.co/3VJmMjlMk6 #OpenSource #Pune, MH #Hiring #CareerArc\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 10:26:31 +0000 2017\"\n"
            + "    }],\n"
            + "    \"FashionDesign\": [{\n"
            + "        \"text\": \"#FashionDesign #InteriorDesign #FashionDesignInstitute #InteriorDesignInstitute #FashionDesignCourse… https://t.co/QTCxiYXR5p\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 10:26:24 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#FashionDesign #InteriorDesign #FashionDesignInstitute #InteriorDesignInstitute #FashionDesignCourse… https://t.co/LoQTHibGfH\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 09:53:13 +0000 2017\"\n"
            + "    }],\n"
            + "    \"InteriorDesign\": [{\n"
            + "        \"text\": \"#FashionDesign #InteriorDesign #FashionDesignInstitute #InteriorDesignInstitute #FashionDesignCourse… https://t.co/QTCxiYXR5p\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 10:26:24 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#FashionDesign #InteriorDesign #FashionDesignInstitute #InteriorDesignInstitute #FashionDesignCourse… https://t.co/LoQTHibGfH\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 09:53:13 +0000 2017\"\n"
            + "    }],\n"
            + "    \"FashionDesignInstitute\": [{\n"
            + "        \"text\": \"#FashionDesign #InteriorDesign #FashionDesignInstitute #InteriorDesignInstitute #FashionDesignCourse… https://t.co/QTCxiYXR5p\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 10:26:24 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#FashionDesign #InteriorDesign #FashionDesignInstitute #InteriorDesignInstitute #FashionDesignCourse… https://t.co/LoQTHibGfH\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 09:53:13 +0000 2017\"\n"
            + "    }],\n"
            + "    \"InteriorDesignInstitute\": [{\n"
            + "        \"text\": \"#FashionDesign #InteriorDesign #FashionDesignInstitute #InteriorDesignInstitute #FashionDesignCourse… https://t.co/QTCxiYXR5p\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 10:26:24 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#FashionDesign #InteriorDesign #FashionDesignInstitute #InteriorDesignInstitute #FashionDesignCourse… https://t.co/LoQTHibGfH\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 09:53:13 +0000 2017\"\n"
            + "    }],\n"
            + "    \"FashionDesignCourse\": [{\n"
            + "        \"text\": \"#FashionDesign #InteriorDesign #FashionDesignInstitute #InteriorDesignInstitute #FashionDesignCourse… https://t.co/QTCxiYXR5p\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 10:26:24 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#FashionDesign #InteriorDesign #FashionDesignInstitute #InteriorDesignInstitute #FashionDesignCourse… https://t.co/LoQTHibGfH\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 09:53:13 +0000 2017\"\n"
            + "    }],\n"
            + "    \"magictricks\": [{\n"
            + "        \"text\": \"The best way to break the ice at a user FGD! #magictricks @fullmazh in #fullpower #workisfun https://t.co/luCZfV6Tvy\",\n"
            + "        \"name\": \"parthadox\",\n"
            + "        \"time\": \"Sat Jun 24 09:57:42 +0000 2017\"\n"
            + "    }],\n"
            + "    \"fullpower\": [{\n"
            + "        \"text\": \"The best way to break the ice at a user FGD! #magictricks @fullmazh in #fullpower #workisfun https://t.co/luCZfV6Tvy\",\n"
            + "        \"name\": \"parthadox\",\n"
            + "        \"time\": \"Sat Jun 24 09:57:42 +0000 2017\"\n"
            + "    }],\n"
            + "    \"workisfun\": [{\n"
            + "        \"text\": \"The best way to break the ice at a user FGD! #magictricks @fullmazh in #fullpower #workisfun https://t.co/luCZfV6Tvy\",\n"
            + "        \"name\": \"parthadox\",\n"
            + "        \"time\": \"Sat Jun 24 09:57:42 +0000 2017\"\n"
            + "    }],\n"
            + "    \"INDvENG\": [{\n"
            + "        \"text\": \"#INDvENG #WomensWorldCup 4 classic boundaries in an over by #mandhana difference in noise levels compared to #men's cricket is palpable!\",\n"
            + "        \"name\": \"Anand_Palsodkar\",\n"
            + "        \"time\": \"Sat Jun 24 09:52:29 +0000 2017\"\n"
            + "    }],\n"
            + "    \"WomensWorldCup\": [{\n"
            + "        \"text\": \"#INDvENG #WomensWorldCup 4 classic boundaries in an over by #mandhana difference in noise levels compared to #men's cricket is palpable!\",\n"
            + "        \"name\": \"Anand_Palsodkar\",\n"
            + "        \"time\": \"Sat Jun 24 09:52:29 +0000 2017\"\n"
            + "    }],\n"
            + "    \"mandhana\": [{\n"
            + "        \"text\": \"#INDvENG #WomensWorldCup 4 classic boundaries in an over by #mandhana difference in noise levels compared to #men's cricket is palpable!\",\n"
            + "        \"name\": \"Anand_Palsodkar\",\n"
            + "        \"time\": \"Sat Jun 24 09:52:29 +0000 2017\"\n"
            + "    }],\n"
            + "    \"men\": [{\n"
            + "        \"text\": \"#INDvENG #WomensWorldCup 4 classic boundaries in an over by #mandhana difference in noise levels compared to #men's cricket is palpable!\",\n"
            + "        \"name\": \"Anand_Palsodkar\",\n"
            + "        \"time\": \"Sat Jun 24 09:52:29 +0000 2017\"\n"
            + "    }],\n"
            + "    \"FashionDesignDiploma\": [{\n"
            + "        \"text\": \"#FashionDesignDiploma #InteriorDesignDiploma #FashionDesignNaviMumbai #InteriorDesignNaviMumbai #FashionTailoring… https://t.co/W6gzv56FfU\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 09:46:57 +0000 2017\"\n"
            + "    }],\n"
            + "    \"InteriorDesignDiploma\": [{\n"
            + "        \"text\": \"#FashionDesignDiploma #InteriorDesignDiploma #FashionDesignNaviMumbai #InteriorDesignNaviMumbai #FashionTailoring… https://t.co/W6gzv56FfU\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 09:46:57 +0000 2017\"\n"
            + "    }],\n"
            + "    \"FashionDesignNaviMumbai\": [{\n"
            + "        \"text\": \"#FashionDesignDiploma #InteriorDesignDiploma #FashionDesignNaviMumbai #InteriorDesignNaviMumbai #FashionTailoring… https://t.co/W6gzv56FfU\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 09:46:57 +0000 2017\"\n"
            + "    }],\n"
            + "    \"InteriorDesignNaviMumbai\": [{\n"
            + "        \"text\": \"#FashionDesignDiploma #InteriorDesignDiploma #FashionDesignNaviMumbai #InteriorDesignNaviMumbai #FashionTailoring… https://t.co/W6gzv56FfU\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 09:46:57 +0000 2017\"\n"
            + "    }],\n"
            + "    \"FashionTailoring\": [{\n"
            + "        \"text\": \"#FashionDesignDiploma #InteriorDesignDiploma #FashionDesignNaviMumbai #InteriorDesignNaviMumbai #FashionTailoring… https://t.co/W6gzv56FfU\",\n"
            + "        \"name\": \"designcareer\",\n"
            + "        \"time\": \"Sat Jun 24 09:46:57 +0000 2017\"\n"
            + "    }],\n"
            + "    \"BeerPorn\": [{\n"
            + "        \"text\": \"#BeerPorn #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #DarkSaison clear, ruby, low… https://t.co/iqvS6vC6Yi\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:44:56 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#BeerPorn #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #DarkSaison clear, ruby, low… https://t.co/iqvS6vC6Yi\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:44:56 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #CaliforniaSunshine crystal… https://t.co/ODVdU1xvuu\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:25:13 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC 7 beers on tap 2 new… https://t.co/35jQyOMosn\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:16:39 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Beergeek\": [{\n"
            + "        \"text\": \"#BeerPorn #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #DarkSaison clear, ruby, low… https://t.co/iqvS6vC6Yi\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:44:56 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #CaliforniaSunshine crystal… https://t.co/ODVdU1xvuu\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:25:13 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC 7 beers on tap 2 new… https://t.co/35jQyOMosn\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:16:39 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Beerlover\": [{\n"
            + "        \"text\": \"#BeerPorn #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #DarkSaison clear, ruby, low… https://t.co/iqvS6vC6Yi\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:44:56 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #CaliforniaSunshine crystal… https://t.co/ODVdU1xvuu\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:25:13 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC 7 beers on tap 2 new… https://t.co/35jQyOMosn\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:16:39 +0000 2017\"\n"
            + "    }],\n"
            + "    \"IndependenceBrewing\": [{\n"
            + "        \"text\": \"#BeerPorn #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #DarkSaison clear, ruby, low… https://t.co/iqvS6vC6Yi\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:44:56 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #CaliforniaSunshine crystal… https://t.co/ODVdU1xvuu\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:25:13 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC 7 beers on tap 2 new… https://t.co/35jQyOMosn\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:16:39 +0000 2017\"\n"
            + "    }],\n"
            + "    \"IBC\": [{\n"
            + "        \"text\": \"#BeerPorn #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #DarkSaison clear, ruby, low… https://t.co/iqvS6vC6Yi\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:44:56 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #CaliforniaSunshine crystal… https://t.co/ODVdU1xvuu\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:25:13 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC 7 beers on tap 2 new… https://t.co/35jQyOMosn\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:16:39 +0000 2017\"\n"
            + "    }],\n"
            + "    \"DarkSaison\": [{\n"
            + "        \"text\": \"#BeerPorn #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #DarkSaison clear, ruby, low… https://t.co/iqvS6vC6Yi\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:44:56 +0000 2017\"\n"
            + "    }],\n"
            + "    \"equality\": [{\n"
            + "        \"text\": \"Support #equality #pridemonth \uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDF08\uD83C\uDF08\\n.\\n.\\n.\\n.\\n#colorful #colors #instagood #igers #igdaily… https://t.co/hZ7fQXXKeg\",\n"
            + "        \"name\": \"chotimirch\",\n"
            + "        \"time\": \"Sat Jun 24 09:41:32 +0000 2017\"\n"
            + "    }],\n"
            + "    \"pridemonth\": [{\n"
            + "        \"text\": \"Support #equality #pridemonth \uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDF08\uD83C\uDF08\\n.\\n.\\n.\\n.\\n#colorful #colors #instagood #igers #igdaily… https://t.co/hZ7fQXXKeg\",\n"
            + "        \"name\": \"chotimirch\",\n"
            + "        \"time\": \"Sat Jun 24 09:41:32 +0000 2017\"\n"
            + "    }],\n"
            + "    \"colorful\": [{\n"
            + "        \"text\": \"Support #equality #pridemonth \uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDF08\uD83C\uDF08\\n.\\n.\\n.\\n.\\n#colorful #colors #instagood #igers #igdaily… https://t.co/hZ7fQXXKeg\",\n"
            + "        \"name\": \"chotimirch\",\n"
            + "        \"time\": \"Sat Jun 24 09:41:32 +0000 2017\"\n"
            + "    }],\n"
            + "    \"colors\": [{\n"
            + "        \"text\": \"Support #equality #pridemonth \uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDF08\uD83C\uDF08\\n.\\n.\\n.\\n.\\n#colorful #colors #instagood #igers #igdaily… https://t.co/hZ7fQXXKeg\",\n"
            + "        \"name\": \"chotimirch\",\n"
            + "        \"time\": \"Sat Jun 24 09:41:32 +0000 2017\"\n"
            + "    }],\n"
            + "    \"instagood\": [{\n"
            + "        \"text\": \"Support #equality #pridemonth \uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDF08\uD83C\uDF08\\n.\\n.\\n.\\n.\\n#colorful #colors #instagood #igers #igdaily… https://t.co/hZ7fQXXKeg\",\n"
            + "        \"name\": \"chotimirch\",\n"
            + "        \"time\": \"Sat Jun 24 09:41:32 +0000 2017\"\n"
            + "    }],\n"
            + "    \"igers\": [{\n"
            + "        \"text\": \"Support #equality #pridemonth \uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDF08\uD83C\uDF08\\n.\\n.\\n.\\n.\\n#colorful #colors #instagood #igers #igdaily… https://t.co/hZ7fQXXKeg\",\n"
            + "        \"name\": \"chotimirch\",\n"
            + "        \"time\": \"Sat Jun 24 09:41:32 +0000 2017\"\n"
            + "    }],\n"
            + "    \"igdaily\": [{\n"
            + "        \"text\": \"Support #equality #pridemonth \uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDFF3️\u200D\uD83C\uDF08\uD83C\uDF08\uD83C\uDF08\\n.\\n.\\n.\\n.\\n#colorful #colors #instagood #igers #igdaily… https://t.co/hZ7fQXXKeg\",\n"
            + "        \"name\": \"chotimirch\",\n"
            + "        \"time\": \"Sat Jun 24 09:41:32 +0000 2017\"\n"
            + "    }],\n"
            + "    \"firebase\": [{\n"
            + "        \"text\": \"Hackathon #firebase #AppFestIN https://t.co/IuetyosCL9\",\n"
            + "        \"name\": \"sonytone\",\n"
            + "        \"time\": \"Sat Jun 24 09:41:07 +0000 2017\"\n"
            + "    }],\n"
            + "    \"AppFestIN\": [{\n"
            + "        \"text\": \"Hackathon #firebase #AppFestIN https://t.co/IuetyosCL9\",\n"
            + "        \"name\": \"sonytone\",\n"
            + "        \"time\": \"Sat Jun 24 09:41:07 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#AppFestIN #Firebase #hackenton https://t.co/aCuHQy1cNN\",\n"
            + "        \"name\": \"ajinkyabadve\",\n"
            + "        \"time\": \"Sat Jun 24 09:37:09 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Audience\": [{\n"
            + "        \"text\": \"Understanding #Audience for #WordPress site by Rohit Langde @mahol | @wcnagpur WordPress #conference #Nagpur https://t.co/ex5dBdODGO\",\n"
            + "        \"name\": \"RohanOnly\",\n"
            + "        \"time\": \"Sat Jun 24 09:40:45 +0000 2017\"\n"
            + "    }],\n"
            + "    \"WordPress\": [{\n"
            + "        \"text\": \"Understanding #Audience for #WordPress site by Rohit Langde @mahol | @wcnagpur WordPress #conference #Nagpur https://t.co/ex5dBdODGO\",\n"
            + "        \"name\": \"RohanOnly\",\n"
            + "        \"time\": \"Sat Jun 24 09:40:45 +0000 2017\"\n"
            + "    }],\n"
            + "    \"conference\": [{\n"
            + "        \"text\": \"Understanding #Audience for #WordPress site by Rohit Langde @mahol | @wcnagpur WordPress #conference #Nagpur https://t.co/ex5dBdODGO\",\n"
            + "        \"name\": \"RohanOnly\",\n"
            + "        \"time\": \"Sat Jun 24 09:40:45 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Nagpur\": [{\n"
            + "        \"text\": \"Understanding #Audience for #WordPress site by Rohit Langde @mahol | @wcnagpur WordPress #conference #Nagpur https://t.co/ex5dBdODGO\",\n"
            + "        \"name\": \"RohanOnly\",\n"
            + "        \"time\": \"Sat Jun 24 09:40:45 +0000 2017\"\n"
            + "    }],\n"
            + "    \"precelebration\": [{\n"
            + "        \"text\": \"#precelebration #eidmubarak #myofficialfriend #cute #shruti \uD83D\uDE18\uD83D\uDE0D\uD83D\uDE18 @… https://t.co/fB3o6QqWlA\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:37:12 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#eidmubarak #precelebration #ofcetime \uD83D\uDE0B\uD83D\uDE04\uD83D\uDE0D\uD83D\uDE18 @ DemandShore https://t.co/mB9h1bWaqg\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:34:50 +0000 2017\"\n"
            + "    }],\n"
            + "    \"eidmubarak\": [{\n"
            + "        \"text\": \"#precelebration #eidmubarak #myofficialfriend #cute #shruti \uD83D\uDE18\uD83D\uDE0D\uD83D\uDE18 @… https://t.co/fB3o6QqWlA\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:37:12 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#eidmubarak #precelebration #ofcetime \uD83D\uDE0B\uD83D\uDE04\uD83D\uDE0D\uD83D\uDE18 @ DemandShore https://t.co/mB9h1bWaqg\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:34:50 +0000 2017\"\n"
            + "    }],\n"
            + "    \"myofficialfriend\": [{\n"
            + "        \"text\": \"#precelebration #eidmubarak #myofficialfriend #cute #shruti \uD83D\uDE18\uD83D\uDE0D\uD83D\uDE18 @… https://t.co/fB3o6QqWlA\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:37:12 +0000 2017\"\n"
            + "    }],\n"
            + "    \"cute\": [{\n"
            + "        \"text\": \"#precelebration #eidmubarak #myofficialfriend #cute #shruti \uD83D\uDE18\uD83D\uDE0D\uD83D\uDE18 @… https://t.co/fB3o6QqWlA\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:37:12 +0000 2017\"\n"
            + "    }],\n"
            + "    \"shruti\": [{\n"
            + "        \"text\": \"#precelebration #eidmubarak #myofficialfriend #cute #shruti \uD83D\uDE18\uD83D\uDE0D\uD83D\uDE18 @… https://t.co/fB3o6QqWlA\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:37:12 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Firebase\": [{\n"
            + "        \"text\": \"#AppFestIN #Firebase #hackenton https://t.co/aCuHQy1cNN\",\n"
            + "        \"name\": \"ajinkyabadve\",\n"
            + "        \"time\": \"Sat Jun 24 09:37:09 +0000 2017\"\n"
            + "    }],\n"
            + "    \"hackenton\": [{\n"
            + "        \"text\": \"#AppFestIN #Firebase #hackenton https://t.co/aCuHQy1cNN\",\n"
            + "        \"name\": \"ajinkyabadve\",\n"
            + "        \"time\": \"Sat Jun 24 09:37:09 +0000 2017\"\n"
            + "    }],\n"
            + "    \"ofcetime\": [{\n"
            + "        \"text\": \"#eidmubarak #precelebration #ofcetime \uD83D\uDE0B\uD83D\uDE04\uD83D\uDE0D\uD83D\uDE18 @ DemandShore https://t.co/mB9h1bWaqg\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:34:50 +0000 2017\"\n"
            + "    }],\n"
            + "    \"waitingforcaptions\": [{\n"
            + "        \"text\": \"#waitingforcaptions #office #face ✋\uD83D\uDC95\uD83D\uDE09 @ Kalyani Nagar https://t.co/Dds10igL8l\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:32:15 +0000 2017\"\n"
            + "    }],\n"
            + "    \"office\": [{\n"
            + "        \"text\": \"#waitingforcaptions #office #face ✋\uD83D\uDC95\uD83D\uDE09 @ Kalyani Nagar https://t.co/Dds10igL8l\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:32:15 +0000 2017\"\n"
            + "    }],\n"
            + "    \"face\": [{\n"
            + "        \"text\": \"#waitingforcaptions #office #face ✋\uD83D\uDC95\uD83D\uDE09 @ Kalyani Nagar https://t.co/Dds10igL8l\",\n"
            + "        \"name\": \"NehaGhaiwat\",\n"
            + "        \"time\": \"Sat Jun 24 09:32:15 +0000 2017\"\n"
            + "    }],\n"
            + "    \"CraftBeer\": [{\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #CaliforniaSunshine crystal… https://t.co/ODVdU1xvuu\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:25:13 +0000 2017\"\n"
            + "    }, {\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC 7 beers on tap 2 new… https://t.co/35jQyOMosn\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:16:39 +0000 2017\"\n"
            + "    }],\n"
            + "    \"CaliforniaSunshine\": [{\n"
            + "        \"text\": \"#CraftBeer #Beergeek #Beerlover #BeerPorn #IndependenceBrewing #IBC #CaliforniaSunshine crystal… https://t.co/ODVdU1xvuu\",\n"
            + "        \"name\": \"ashtiwfoodie\",\n"
            + "        \"time\": \"Sat Jun 24 09:25:13 +0000 2017\"\n"
            + "    }],\n"
            + "    \"PrideMonth\": [{\n"
            + "        \"text\": \"#PrideMonth Special. No Love Barred-June 27. Screening 2 beautiful short films &amp; 1 feature film. An ode to love&amp;sol… https://t.co/joKoh63Ihk\",\n"
            + "        \"name\": \"lostthepl0t\",\n"
            + "        \"time\": \"Sat Jun 24 09:15:33 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Demonetisation\": [{\n"
            + "        \"text\": \"@virsanghvi \uD83D\uDC46Despite TYRANNY sought to be imposed via #Demonetisation #SwacchBharat #Aadhaar #GST #Majoritarianism… https://t.co/MylvSIczWH\",\n"
            + "        \"name\": \"SarahTitus0306\",\n"
            + "        \"time\": \"Sat Jun 24 09:09:11 +0000 2017\"\n"
            + "    }],\n"
            + "    \"SwacchBharat\": [{\n"
            + "        \"text\": \"@virsanghvi \uD83D\uDC46Despite TYRANNY sought to be imposed via #Demonetisation #SwacchBharat #Aadhaar #GST #Majoritarianism… https://t.co/MylvSIczWH\",\n"
            + "        \"name\": \"SarahTitus0306\",\n"
            + "        \"time\": \"Sat Jun 24 09:09:11 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Aadhaar\": [{\n"
            + "        \"text\": \"@virsanghvi \uD83D\uDC46Despite TYRANNY sought to be imposed via #Demonetisation #SwacchBharat #Aadhaar #GST #Majoritarianism… https://t.co/MylvSIczWH\",\n"
            + "        \"name\": \"SarahTitus0306\",\n"
            + "        \"time\": \"Sat Jun 24 09:09:11 +0000 2017\"\n"
            + "    }],\n"
            + "    \"GST\": [{\n"
            + "        \"text\": \"@virsanghvi \uD83D\uDC46Despite TYRANNY sought to be imposed via #Demonetisation #SwacchBharat #Aadhaar #GST #Majoritarianism… https://t.co/MylvSIczWH\",\n"
            + "        \"name\": \"SarahTitus0306\",\n"
            + "        \"time\": \"Sat Jun 24 09:09:11 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Majoritarianism\": [{\n"
            + "        \"text\": \"@virsanghvi \uD83D\uDC46Despite TYRANNY sought to be imposed via #Demonetisation #SwacchBharat #Aadhaar #GST #Majoritarianism… https://t.co/MylvSIczWH\",\n"
            + "        \"name\": \"SarahTitus0306\",\n"
            + "        \"time\": \"Sat Jun 24 09:09:11 +0000 2017\"\n"
            + "    }],\n"
            + "    \"hiring\": [{\n"
            + "        \"text\": \"We're #hiring! Click to apply: Sr Technical Supp Analyst - India - https://t.co/wph1jax1XY #IT #Pune #Job #Jobs\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 09:08:02 +0000 2017\"\n"
            + "    }],\n"
            + "    \"IT\": [{\n"
            + "        \"text\": \"We're #hiring! Click to apply: Sr Technical Supp Analyst - India - https://t.co/wph1jax1XY #IT #Pune #Job #Jobs\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 09:08:02 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Job\": [{\n"
            + "        \"text\": \"We're #hiring! Click to apply: Sr Technical Supp Analyst - India - https://t.co/wph1jax1XY #IT #Pune #Job #Jobs\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 09:08:02 +0000 2017\"\n"
            + "    }],\n"
            + "    \"Jobs\": [{\n"
            + "        \"text\": \"We're #hiring! Click to apply: Sr Technical Supp Analyst - India - https://t.co/wph1jax1XY #IT #Pune #Job #Jobs\",\n"
            + "        \"name\": \"tmj_inp_jobs\",\n"
            + "        \"time\": \"Sat Jun 24 09:08:02 +0000 2017\"\n"
            + "    }]\n"
            + "}";

    List<String> products = new ArrayList<String>();
    HashMap<String, JSONArray> individualData;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
        individualData = new HashMap<>();

        JSONObject object = null;
        JSONArray objectDetails = null;
        String key;
        int i;
        try {
            object = new JSONObject(data);
            Iterator<String> keys = object.keys();
            while (keys.hasNext()) {
                key = keys.next();
                products.add(key);
                objectDetails = (JSONArray) object.get(key);
                individualData.put(key, objectDetails);
            }
        } catch (JSONException e) {
            e.printStackTrace();
        }


        lv = (ListView) findViewById(R.id.list_view);
        inputSearch = (EditText) findViewById(R.id.inputSearch);

        // Adding items to listview
        adapter = new ArrayAdapter<String>(this, R.layout.list_item, R.id.product_name, products);
        lv.setAdapter(adapter);
        lv.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Intent intent = new Intent(MainActivity2.this, MainActivity.class);
                intent.putExtra("DATA", individualData.get(products.get(position)).toString());
                startActivity(intent);
            }
        });

        inputSearch.addTextChangedListener(new TextWatcher() {

            @Override
            public void onTextChanged(CharSequence cs, int arg1, int arg2, int arg3) {
                // When user changed the Text
                MainActivity2.this.adapter.getFilter().filter(cs);
            }

            @Override
            public void beforeTextChanged(CharSequence arg0, int arg1, int arg2,
                    int arg3) {
                // TODO Auto-generated method stub

            }

            @Override
            public void afterTextChanged(Editable arg0) {
                // TODO Auto-generated method stub
            }
        });
    }


}